added ability to change the redstone lamp turning off delay(default 0)
Team-Symphony/Harmony pull request #20
Opened 2024-10-07 21:21 UTC by RandmlyCoding

2024-10-14 18:48 UTC, Flatkat commented
LGTM! I would just add a tooltip saying what the default vanilla behaviour is, with the code not running if you set it to that number (to avoid issues).
Or well, even better, just make this a bool, i dont think people will be interested in tweaking this behaviour with smth more complex than a true or false, and avoids confusion, since a 0 wouldnt disable the feature as it would normally be expected in these kinds of situations.

2024-10-15 19:56 UTC, Flatkat commented
Please, properly capitalize the text and use a tooltip instead of a comment.
For that, use the following on the lang file: `"modid.midnightconfig.name.tooltip":"I am a tooltip uwu \nI am a new line",`
For more information, visit MidnightLib's wiki: https://www.midnightdust.eu/wiki/midnightlib/

2024-10-15 20:44 UTC, RandmlyCoding commented
oh, i missed that part of the documentation. Its fixed now

2024-10-17 08:14 UTC, Flatkat commented
Will test the changes i made when im free to do so

2024-10-17 08:14 UTC, Flatkat commented
Still the code may get re-reviewed soon prior to merge, or after merging. we will see

2024-10-28 00:51 UTC, axialeaa commented on src/main/java/dev/symphony/harmony/mixin/redstone/ChangeRedstoneLampDelay.java
> +    @Inject(method = "neighborUpdate",at = @At("HEAD"), cancellable = true)
Injecting at head and using `ci.cancel()` is generally unfavorable as it causes other modder's changes to completely fail to apply without any warning of a conflict.

There are several things you can do here, but my recommendation would be to use `@WrapOperation` at `"INVOKE"` targeting the call to `scheduleBlockTick()`. That call will then be passed into the arg `original`, which you can call by default if the config option is disabled.

If the config option is *enabled*, you can just call `scheduledTick()` directly. No need to copy and paste any code from inside that method, as `scheduledTick()` gets called as part of the schedule block tick process anyway.

2024-10-28 00:52 UTC, axialeaa commented on src/main/java/dev/symphony/harmony/mixin/redstone/ChangeRedstoneLampDelay.java
> +        ci.cancel();
At any rate, this `ci.cancel()` should be moved inside the bracket. Currently it's preventing the lamp from ever changing state regardless of the option setting.

2024-10-28 00:54 UTC, axialeaa requested changes

2024-10-28 00:54 UTC, axialeaa commented on src/main/java/dev/symphony/harmony/mixin/redstone/ChangeRedstoneLampDelay.java
> +    @Inject(method = "neighborUpdate",at = @At("HEAD"), cancellable = true)
Injecting at head and using `ci.cancel()` is generally unfavorable as it causes other modder's changes to completely fail to apply without any warning of a conflict.

There are several things you can do here, but my recommendation would be to use `@WrapOperation` at `"INVOKE"` targeting the call to `scheduleBlockTick()`. That call will then be passed into the arg `original`, which you can call by default if the config option is disabled.

If the config option is *enabled*, you can just call `scheduledTick()` directly. No need to copy and paste any code from inside that method, as `scheduledTick()` gets called as part of the schedule block tick process anyway.

2024-10-28 00:54 UTC, axialeaa commented on src/main/java/dev/symphony/harmony/mixin/redstone/ChangeRedstoneLampDelay.java
> +        ci.cancel();
At any rate, this `ci.cancel()` should be moved inside the bracket. Currently it's preventing any of the neighbor update code from running regardless of the option setting.

2024-10-28 00:59 UTC, axialeaa commented
Sorry for the mess just then; I submitted them as single comments instead of as a review!

2024-10-29 08:20 UTC, axialeaa approved these changes
Excellent, looks good to me

2024-10-29 21:14 UTC, Flatkat commented
Just tested and works on 1.21.3, no port required. Merging

2024-10-29 21:15 UTC, merged

2024-11-12 18:53 UTC, RandmlyCoding commented
#20