Trident buff and elytra deactivates underwater
Team-Symphony/Harmony pull request #35
Opened 2024-10-18 22:03 UTC by Flatkat

Added features:
-Riptide now adds acceleration while underwater
-Longer Riptide animation (riptide accelerates during its animation)
-Elytra deactivates when going underwater or inside of lava

TODO:
-Find the proper values to have this balanced
-Change the config value so instead of 0.1F or 0.01F is a more familiar scale like from 0 to a 100 or 200 in a slider, then divide by a 10 exponent from behind, to make it easier to configure for users
-Make Elytra get disabled when submerged in any liquid, not just water or lava (for better mod support)

2024-10-22 20:28 UTC, axialeaa requested changes

2024-10-22 20:28 UTC, axialeaa commented on src/main/java/dev/symphony/harmony/mixin/transportation/LivingEntityMixin.java
> +    @Redirect(method = "tickFallFlying", at = @At(value = "INVOKE", target = "Lnet/minecraft/entity/LivingEntity;hasStatusEffect(Lnet/minecraft/registry/entry/RegistryEntry;)Z"))
This can be changed to a `@WrapOperation`, which allows you to return the original value if the config option is disabled. This is much better for compatibility as it stacks with other changes and doesn't crash when another mod injects at the same target.

2024-11-02 18:45 UTC, MonkaKokosowa approved these changes, later dismissed

2024-11-26 12:44 UTC, MonkaKokosowa approved these changes, later dismissed

2024-11-29 15:40 UTC, axialeaa requested changes

2024-11-29 15:40 UTC, axialeaa commented on src/main/java/dev/symphony/harmony/mixin/combat/tridents_return_from_void/TridentEntityMixin.java
> +                if (!this.dealtDamage && this.getBlockPos().getY() < 1 && this.getWorld().getDimensionEntry().getKey().get().getValue().toString().contains("minecraft:the_end")) {
This long chain of calls to find the end dimension can be replaced by `this.getWorld().getRegistryKey() == World.END`. Other than that, looks good to me!

2024-12-01 14:53 UTC, axialeaa submitted a review, later dismissed

2024-12-01 15:22 UTC, axialeaa submitted a review, later dismissed

2024-12-01 16:13 UTC, axialeaa submitted a review, later dismissed

2024-12-01 16:18 UTC, axialeaa approved these changes

2024-12-01 16:19 UTC, Flatkat commented
Truly one of the Github moments of all time

2024-12-01 18:20 UTC, MonkaKokosowa approved these changes

2024-12-01 19:19 UTC, merged